# Site wide configuration

title: Oolong Times
locale: en_US
description: repo of articles - links to great technical reads, blogs, news, mailing list threads, videos and more
search: true
url: //swathimystery.github.io/oolong


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Swathi Venkatachala
  avatar: bio-photo.jpg
  email: swatzdev@gmail.com
  github: SwathiMystery
  stackexchange: http://stackoverflow.com/users/2248792/swathi
  linkedin: swathimystery
  google:
    plus: SwathiVenkatachala
